#!/bin/bash

# 1. Wait for wp-config.php (generated by the wordpress container)
echo "Waiting for wp-config.php..."
while [ ! -f /var/www/html/wp-config.php ]; do
    sleep 2
done
echo "wp-config.php found."

# 2. Wait for Database using mysql client directly with SSL disabled
echo "Waiting for database connection..."
while ! mysql -h db -u wordpress -ppassword -e "SELECT 1" --skip-ssl > /dev/null 2>&1; do
    echo "Waiting for DB..."
    sleep 3
done
echo "Database connection established."

# 3. Check if WordPress is installed and install if needed
if ! wp core is-installed --allow-root --quiet; then
    echo "Installing WordPress..."
    wp core install \
        --url="http://localhost:8500" \
        --title="WooCommerce Dev" \
        --admin_user="admin" \
        --admin_password="password" \
        --admin_email="test@example.com" \
        --skip-email \
        --allow-root
else
    echo "WordPress is already installed."
fi

# 4. Install WooCommerce if not present
if ! wp plugin is-installed woocommerce --allow-root; then
    echo "Installing WooCommerce..."
    wp plugin install woocommerce --activate --allow-root
else
    echo "WooCommerce is already installed."
fi

# 5. Activate our plugin
echo "Activating WooCommerce Tweaks..."
wp plugin activate woocommerce-tweaks --allow-root

# 6. Configure Store (Currency, Payment methods)
echo "Configuring Store Settings..."
wp eval-file /setup-store.php --allow-root

# 7. Create a Test Product if none exists
if [ $(wp post list --post_type=product --format=count --allow-root) -eq 0 ]; then
    echo "Creating Test Product..."
    PRODUCT_ID=$(wp post create --post_type=product --post_title="Produto de Teste" --post_status=publish --porcelain --allow-root)
    wp post meta update $PRODUCT_ID _regular_price 100 --allow-root
    wp post meta update $PRODUCT_ID _price 100 --allow-root
    wp post meta update $PRODUCT_ID _virtual yes --allow-root
    wp post meta update $PRODUCT_ID _downloadable yes --allow-root
    echo "Created 'Produto de Teste' ($PRODUCT_ID) - R$ 100,00"
else
    echo "Test product already exists."
fi

# 8. Fix permissions (since we ran as root)
echo "Fixing permissions..."
chown -R www-data:www-data /var/www/html/wp-content

echo "Provisioning complete! Login at http://localhost:8500/wp-admin"
echo "User: admin | Pass: password"
